### ISSUE TITLE
Bump Nx and release 0.3.1 to match Bumblebee

### ISSUE THREAD

**Issue by bianchidotdev** [livebook-dev/kino_bumblebee#33]
On a fresh install of livebook, following the Bumblebee docs, I am able to start use bumblebee just fine. However, trying to add a smart cell for a Neural Network task (really just adding the automatic adding of `kino_bumblebee`) results in a Hex dependency resolution failure.

I believe this is because Bumblebee now relies upon `{:nx, "~> 0.6.0"}` but `kino_bumblebee` specifies `{:nx, "~> 0.5"}`

While I was able to just downgrade Bumblebee to `0.3.0` and move on, if we release a new version of `kino_bumblebee` with Nx `0.6.*`, then I think we'll help the on-boarding process for Livebook users.

Full error:
```
Resolving Hex dependencies...
Resolution completed in 0.099s
Because bumblebee >= 0.3.1 depends on nx ~> 0.6.0 and kino_bumblebee >= 0.2.0 depends on nx ~> 0.5.0, bumblebee >= 0.3.1 is incompatible with kino_bumblebee >= 0.2.0.
And because your app depends on bumblebee ~> 0.3.1, kino_bumblebee >= 0.2.0 is forbidden.
So, because your app depends on kino_bumblebee ~> 0.3.0, version solving failed.
** (Mix.Error) Hex dependency resolution failed
    (mix 1.15.2) lib/mix.ex:577: Mix.raise/2
    (mix 1.15.2) lib/mix/dep/converger.ex:141: Mix.Dep.Converger.all/4
    (mix 1.15.2) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
    (mix 1.15.2) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix 1.15.2) lib/mix/tasks/deps.get.ex:34: Mix.Tasks.Deps.Get.run/1
    (mix 1.15.2) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.2) lib/mix.ex:874: anonymous fn/5 in Mix.install/2
    #cell:setup:1: (file)
```

**Comment by bianchidotdev** [comment]
Actually, I think master currently would be OK given that the version pinning is less restrictive now. Ideally, we'd just need to release a new version of this library.

**Comment by bianchidotdev** [comment]
Actually, actually, I guess we'd want to probably update the task cell map with new models before releasing `0.3.1` so it's up to date.

**Comment by josevalim** [comment]
Yeah, we have updated everything already, we just need to ship a new version of Livebook.

btw, this error only happens if you add bumblebee before, right? If you use the smart cell without adding bumblebee before hand, it all works?

**Comment by bianchidotdev** [comment]
Very cool. Thanks. 
Confirmed that it does not error out when just trying to use the smart cell without setting up the mix deps first. It's only an issue if you explicitly specify Bumblebee `0.3.1` in the deps.

**Comment by josevalim** [comment]
Cool, thank you! Updated does will be shipped soon :)
